# mysql configuration
spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    ttl: PT24H
    cacheNullValues: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: [db_contactbook]
  application:
    name: contactbook
    host: ${APP_HOST:http://localhost:8080}
  datasource:
    url: jdbc:mysql://localhost:3306/db_contactbook
    username: root
    password: root
    driver: com.mysql.jdbc.Driver

db:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/db_contactbook
  username: root
  password: root

info:
  application:

server:
  port: 8080
  profile: ${profile:dev}
  servlet:
        context-path: /api

exception:
    contactNotFound: "Contact not found in contact book"
    contactAlreadyExists: "Contact already exists"
    nositecode: "Sitecode not present"
    hostnotallowed: "Not valid host"

controller:
    path:
        contact: "contact"
        contactItem: "contact/{id}"

cache:
  key:
